markdown: kramdown
title:
author:
  name: ProfeJulianLasso
  email: julian.lasso@sofka.com.co
show_excerpts: false
theme: minima
# remote_theme: pages-themes/minimal@v0.2.0
# plugins:
# - jekyll-remote-theme